prefs={
  width=1024,
  height=768,
  maximizedWindow=false,
  fullscreen=false,
  noImages = false,
  creatureShadows = true,
  creatureAnimations = true,
  asciiSize = 14,
  fontSize = 14,
  descFontSize = 12,
  soundVolume = 100,
  musicVolume = 100,
  mouseMovesMap = true,
  captureMouse = true,
  autosaveTurns=false,
  noSmoothMovement=false,
  noSmoothCamera=false,
  statsOnSidebar=false,
  plainFonts=false,
  bigButtons=false,
  healthbars=true,
  minimap=true,
  lastMods={},
  uiScale=1,
  vsync=true,
  autoLevel=false
}

require "keybindings"