keybindings = {
  escape={"escape",description="Back/Escape",category="Miscellaneous"},
  enter={"return","kpenter",description="Select",category="Miscellaneous"},
  north={"kp8","up",description="North/Up",category="Movement"},
  northeast={"kp9",description="Northeast",category="Movement"},
  east={"kp6","right",description="East/Right",category="Movement"},
  southeast={"kp3",description="Southeast",category="Movement"},
  south={"kp2","down",description="South/Down",category="Movement"},
  southwest={"kp1",description="Southwest",category="Movement"},
  west={"kp4","left",description="West/Left",category="Movement"},
  northwest={"kp7",description="Northwest",category="Movement"},
  wait={"kp5","space",description="Wait",category="Movement"},
  examine={"x",description="Examine/Target",category="Game Commands"},
  spell={"z",description="View Abilities",category="Game Commands"},
  charScreen = {"c",description="View Character Screen",category="Game Commands"},
  messages = {"h",description="View Previous Messages",category="Game Commands"},
  ranged = {"f",description="Ranged Attack",category="Game Commands"},
  recharge = {"r",description="Reload/Recharge",category="Game Commands"},
  nextTarget = {"tab",description="Switch Targets",category="Game Commands"},
  pickup={"g",description="Pick Up Items",category="Game Commands"},
  inventory={"i",description="View Inventory",category="Game Commands"},
  equip={"w",description="Equip Item",category="Inventory"},
  use={"u",description="Use Item",category="Inventory"},
  drop={"d",description="Drop Item",category="Inventory"},
  throw={"t",description="Throw Item",category="Inventory"},
  action={"a",description="Use Nearby Map Feature",category="Game Commands"},
  crafting={"m",description="View Crafting Screen",category="Inventory"},
  yes={"y",description="Yes/Confirm",category="Miscellaneous"},
  no={"n",description="No/Deny",category="Miscellaneous"},
  camera_north={description="Move Camera North",category="Camera"},
  camera_northeast={description="Move Camera Northeast",category="Camera"},
  camera_east={description="Move Camera East",category="Camera"},
  camera_southeast={description="Move Camera Southeast",category="Camera"},
  camera_south={description="Move Camera South",category="Camera"},
  camera_southwest={description="Move Camera Southwest",category="Camera"},
  camera_west={description="Move Camera West",category="Camera"},
  camera_northwest={description="Move Camera Northwest",category="Camera"},
  zoomIn={"=",description="Zoom In",category="Camera"},
  zoomOut={"-",description="Zoom Out",category="Camera"},
}
keybindings_order = {"Movement","Game Commands","Inventory","Camera","Miscellaneous"}