prefs={
  width=1024,
  height=768,
  maximizedWindow=false,
  fullscreen=false,
  noImages = false,
  creatureShadows = true,
  creatureAnimations = true,
  asciiSize = 14,
  fontSize = 14,
  descFontSize = 12,
  soundVolume = 100,
  musicVolume = 100,
  mouseMovesMap = true,
  mouseScrollTime = 0.01,
  captureMouse = true,
  autosaveTurns=false,
  noSmoothMovement=false,
  noSmoothCamera=false,
  plainFonts=false,
  bigButtons=false,
  healthbars=true,
  minimap=true,
  lastMods={},
  uiScale=1,
  vsync=true,
  autoLevel=false,
  prefsVersion=1 --Changing this value will cause all preferences to be deleted on next launch, defaulting everything to default. Only use this if absolutely necessary, and warn users in your update notes if you do. You can add new preferences and keybindings and they will automatically be added to the user's prefs file without changing this value.
}

require "keybindings"